version: "3.7"

services:
    db:
        image: postgres
        volumes:
            - ./web/data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: ./web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./web:/usr/src/app/
        ports: 
            - "8000:8000"
        env_file: ./web/.env.dev
        depends_on:
            - db